"""Replace placeholder Experiment 2 section in Chapter5.tex with actual results."""
from pathlib import Path

f = Path("publication/thesis/Cairo_University_Faculty_of_Engineering_Thesis/MainMatter/Chapter5.tex")
content = f.read_text(encoding="utf-8")

# Find and replace everything from the Experiment 2 section header onwards
marker = r"\section{Experiment 2 Results --- Prompt Design Ablation on Full-Page Datasets}"
idx = content.find(marker)
if idx < 0:
    print("Marker not found!")
    exit(1)

keep = content[:idx]

new_section = (
    r"\section{Experiment 2 Results --- Prompt Design Study}" + "\n"
    r"\label{sec:res_exp2}" + "\n"
    "\\%---------------------------------------------------------------------------\n\n"
    r"Experiment~2 evaluates eight prompt configurations on thirteen datasets"
    "\n(PATS-A01 eight fonts, KHATT, KHATT-Paragraph, Yarmouk, Muharaf, Historical)\n"
    r"using Qwen3-4B-Instruct-2507. Four prompt styles (base, conservative,"
    "\nerror-pattern, error-pattern+conservative) are crossed with two retrieval\n"
    r"strategies (zero-shot and BM25 RAG), yielding eight trials T1--T8."
    "\nAll metrics: normal samples only, diacritics stripped.\n\n"

    r"\begin{table}[htbp]" + "\n"
    r"  \centering" + "\n"
    r"  \caption{Experiment~2: PATS-A01 macro-average and KHATT CER per trial" + "\n"
    r"           (normal samples only, diacritics stripped)." + "\n"
    r"           $\dagger$ T7 catastrophic: template-tag injection; excluded.}" + "\n"
    r"  \label{tab:exp2_results}" + "\n"
    r"  \begin{tabularx}{\textwidth}{lllXXXX}" + "\n"
    r"    \toprule" + "\n"
    r"    \textbf{\#} & \textbf{Style} & \textbf{RAG}" + "\n"
    r"      & \textbf{PATS CER} & \textbf{$\Delta$PATS}" + "\n"
    r"      & \textbf{KHATT CER} & \textbf{$\Delta$KHATT} \\" + "\n"
    r"    \midrule" + "\n"
    r"    OCR & baseline      & ---  &  5.57 & ---    & 34.24 & --- \\" + "\n"
    r"    T1  & Base          & No   &  5.84 & $+$0.27 & 33.25 & $-$0.99 \\" + "\n"
    r"    T2  & Base          & Yes  &  5.44 & $-$0.13 & 33.82 & $-$0.42 \\" + "\n"
    r"    \textbf{T3}  & \textbf{Conservative} & \textbf{No} & \textbf{5.27} & \textbf{$-$0.30} & 32.93 & $-$1.31 \\" + "\n"
    r"    T4  & Conservative  & Yes  & 27.02 & $+$21.45 & 32.69 & $-$1.55 \\" + "\n"
    r"    T5  & Error-pat.    & No   &  5.85 & $+$0.28 & 32.90 & $-$1.34 \\" + "\n"
    r"    T6  & Error-pat.    & Yes  & 19.64 & $+$14.07 & 32.64 & $-$1.60 \\" + "\n"
    r"    T7$\dagger$ & Err-pat+Cons. & No & 190.60 & $\dagger$ & 51.64 & $\dagger$ \\" + "\n"
    r"    T8  & Err-pat+Cons. & Yes  & 46.56 & $+$40.99 & 32.54 & $-$1.70 \\" + "\n"
    r"    \bottomrule" + "\n"
    r"  \end{tabularx}" + "\n"
    r"\end{table}" + "\n\n"

    r"\textbf{T3 (conservative zero-shot) achieves the best PATS result}: 5.27\%"
    "\n($-$0.30~pp vs.\\ OCR baseline, $-$5.4\\% relative), outperforming all\n"
    r"Experiment~1 phases including P8 RAG (5.45\%), without retrieval overhead."
    "\nT2 (base+RAG) is best overall: 5.44\\% PATS and 33.82\\% KHATT.\n\n"
    r"Error-pattern trials (T4--T8) cause catastrophic per-font failures:"
    "\nT7 suffers template-tag injection (190.60\\%); T4 causes Thuluth CER to\n"
    r"jump to 116.3\%; T6 causes Andalus to 59.77\%. Adding error-pattern"
    "\ncontext to complex prompts destabilises output formatting.\n\n"
    r"\textbf{Decision:} T2 (base+RAG) adopted for Experiment~3."
    "\n\n"

    r"\begin{table}[htbp]" + "\n"
    r"  \centering" + "\n"
    r"  \caption{Experiment~2 per-font PATS CER for T1, T2, T3 (normal samples" + "\n"
    r"           only, diacritics stripped). Best per font in \textbf{bold}.}" + "\n"
    r"  \label{tab:exp2_pats_per_font}" + "\n"
    r"  \begin{tabularx}{\textwidth}{lXXXX}" + "\n"
    r"    \toprule" + "\n"
    r"    \textbf{Font} & \textbf{OCR} & \textbf{T1} & \textbf{T2} & \textbf{T3} \\" + "\n"
    r"    \midrule" + "\n"
    r"    Akhbar       &  2.12 & 2.71 & 2.97 & \textbf{2.32} \\" + "\n"
    r"    Simplified   &  2.94 & 2.94 & 3.01 & \textbf{2.43} \\" + "\n"
    r"    Traditional  &  3.63 & 2.97 & 3.07 & \textbf{2.58} \\" + "\n"
    r"    Arial        &  3.65 & 4.50 & 3.83 & \textbf{3.74} \\" + "\n"
    r"    Naskh        &  4.10 & 4.26 & 4.36 & \textbf{3.69} \\" + "\n"
    r"    Tahoma       &  5.82 & 6.14 & 6.20 & \textbf{5.54} \\" + "\n"
    r"    Thuluth      & 10.21 & 10.93 & \textbf{9.68} & 10.23 \\" + "\n"
    r"    Andalus      & 12.12 & 12.26 & \textbf{10.42} & 11.68 \\" + "\n"
    r"    \midrule" + "\n"
    r"    \textbf{Avg} & \textbf{5.57} & 5.84 & 5.44 & \textbf{5.27} \\" + "\n"
    r"    KHATT        & 34.24 & 33.25 & 33.82 & 32.93 \\" + "\n"
    r"    \bottomrule" + "\n"
    r"  \end{tabularx}" + "\n"
    r"\end{table}" + "\n\n"

    "%%---------------------------------------------------------------------------\n"
    r"\section{Experiment 3 Results --- Final Multi-Model, Multi-Domain}" + "\n"
    r"\label{sec:res_exp3}" + "\n"
    "\\%---------------------------------------------------------------------------\n\n"
    r"Experiment~3 uses T2 (base+RAG) across four models, two OCR sources,"
    "\nand three dataset groups. CER$\\dagger$ = after runaway correction\n"
    r"(threshold $3.0{\times}$GT length)."
    "\n\n"

    r"\subsection{3A: Model Comparison}" + "\n"
    r"\label{subsec:res_exp3_models}" + "\n\n"
    r"\begin{table}[htbp]" + "\n"
    r"  \centering" + "\n"
    r"  \caption{Experiment~3A: four models on validation set, Qaari OCR, T2." + "\n"
    r"           FP = full-page group (KHATT-Para+Yarmouk+Muharaf+Historical)," + "\n"
    r"           OCR baseline 86.50\%.}" + "\n"
    r"  \label{tab:exp3_models}" + "\n"
    r"  \begin{tabularx}{\textwidth}{llXXXXX}" + "\n"
    r"    \toprule" + "\n"
    r"    \textbf{Model} & \textbf{Params} & \textbf{PATS} & \textbf{PATS$\dagger$}" + "\n"
    r"      & \textbf{KHATT} & \textbf{KHATT$\dagger$} & \textbf{FP$\dagger$} \\" + "\n"
    r"    \midrule" + "\n"
    r"    OCR Baseline & --- &  5.57 & ---   & 34.24 & ---   & 86.50 \\" + "\n"
    r"    Qwen3-4B     & 4B  &  5.44 & \textbf{5.44} & \textbf{33.82} & \textbf{33.82} & \textbf{68.18} \\" + "\n"
    r"    Qwen3-14B    & 14B & 15.30 & 5.60  & 175.69 & 35.55 & 88.51 \\" + "\n"
    r"    Gemma-3-4B   & 4B  &  7.47 & 7.47  & 36.14 & 36.14 & 71.12 \\" + "\n"
    r"    Gemma-3-12B  & 12B &  5.33 & \textbf{5.33} & 35.98 & 35.98 & 70.01 \\" + "\n"
    r"    \bottomrule" + "\n"
    r"  \end{tabularx}" + "\n"
    r"\end{table}" + "\n\n"
    r"Qwen3-14B suffers a runaway epidemic: 175.69\% KHATT raw, 35.55\% with"
    "\ncorrector --- still worse than Qwen3-4B (33.82\\%). Gemma-3-12B best\n"
    r"PATS$\dagger$ (5.33\%); Qwen3-4B best KHATT + FP."
    "\n\n"

    r"\subsection{3B: OCR Source Impact}" + "\n"
    r"\label{subsec:res_exp3_ocr}" + "\n\n"
    r"\begin{table}[htbp]" + "\n"
    r"  \centering" + "\n"
    r"  \caption{Experiment~3B: Qwen3-4B, T2, Qaari vs.\ Gemma-3 VLM OCR." + "\n"
    r"           CER$\dagger$ = runaway-corrected.}" + "\n"
    r"  \label{tab:exp3_ocr_source}" + "\n"
    r"  \begin{tabularx}{\textwidth}{llXXX}" + "\n"
    r"    \toprule" + "\n"
    r"    \textbf{Group} & \textbf{Src} & \textbf{OCR CER} & \textbf{Corr.\ CER$\dagger$} & \textbf{$\Delta$} \\" + "\n"
    r"    \midrule" + "\n"
    r"    PATS avg & Qaari &  5.57 &  5.44 & $-$0.13 \\" + "\n"
    r"    PATS avg & Gemma & 170.63 & 124.44 & (broken) \\" + "\n"
    r"    KHATT    & Qaari & 34.24 & 33.82 & $-$0.42 \\" + "\n"
    r"    KHATT    & Gemma & 75.78 & 71.24 & $-$4.54 \\" + "\n"
    r"    Full-page & Qaari & 86.50 & 68.18 & $-$18.32 \\" + "\n"
    r"    Full-page & Gemma & 87.33 & 64.28 & $-$23.05 \\" + "\n"
    r"    \bottomrule" + "\n"
    r"  \end{tabularx}" + "\n"
    r"\end{table}" + "\n\n"
    r"Gemma VLM is broken on PATS line strips (170.63\%) but comparable to"
    "\nQaari on full-page documents; corrected results slightly better (64.28\\%\n"
    r"vs.\ 68.18\%)."
    "\n\n"

    r"\subsection{3C: Generalization}" + "\n"
    r"\label{subsec:res_exp3_gen}" + "\n\n"
    r"\begin{table}[htbp]" + "\n"
    r"  \centering" + "\n"
    r"  \caption{Experiment~3C: BM Arabic Benchmark + Kitab Benchmark" + "\n"
    r"           (Qwen3-4B, T2, runaway-corrected).}" + "\n"
    r"  \label{tab:exp3_generalization}" + "\n"
    r"  \begin{tabularx}{\textwidth}{llXXX}" + "\n"
    r"    \toprule" + "\n"
    r"    \textbf{Benchmark} & \textbf{Src} & \textbf{OCR CER} & \textbf{Corr.\ CER$\dagger$} & \textbf{$\Delta$} \\" + "\n"
    r"    \midrule" + "\n"
    r"    BM Overall & Qaari & 95.31 & \textbf{85.11} & $-$10.20 \\" + "\n"
    r"    BM Overall & Gemma & 68.49 & \textbf{61.13} & $-$7.36 \\" + "\n"
    r"    Kitab Overall & Qaari & 49.28 & \textbf{40.73} & $-$8.55 \\" + "\n"
    r"    Kitab Overall & Gemma & 79.45 & \textbf{60.07} & $-$19.38 \\" + "\n"
    r"    \bottomrule" + "\n"
    r"  \end{tabularx}" + "\n"
    r"\end{table}" + "\n\n"
    r"LLM correction generalises robustly to unseen benchmarks."
    "\nLow-CER subsets (kitab-arabicocr 1.80\\%) are harmed, consistent with\n"
    r"the over-correction finding confirmed across all three experiments."
    "\n"
)

new_content = keep + new_section
f.write_text(new_content, encoding="utf-8")
print(f"Done. Chapter5.tex: {len(new_content)} chars, {len(new_content.splitlines())} lines")
